/**
 * This class is generated by jOOQ
 */
package lab.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class FileMetadata implements Serializable {
	private static final long serialVersionUID = -1953963826;
	
	private Integer fileId;
	private String name;
	private String pathLower;
	private String pathDisplay;
	private Integer enclosingFolderId;
	private Integer size;
	private String serverCreatedAt;
	private String serverChangedAt;
	private Integer ownerId;
}
